# Generated by Django 5.0 on 2024-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajlar',
            name='subject',
            field=models.TextField(default='No Subject'),
        ),
        migrations.AlterField(
            model_name='mesajlar',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
